### ISSUE TITLE
Missing languages in output 

### ISSUE THREAD

**Issue by matteoLorenzini** [gtadigital/SPARQL_Data_Analysis#2]
Some languages as Polish or Romanian are missing from the SPARQL output. Check the language declaration in SPARQL query.

**Comment by thomashaensli** [comment]
If it is too much of a trouble, we can skip it... The only thing that would be handy, was if we can fetch the lang-code for the preferred term, 

For ex: 
http://vocab.getty.edu/tgn/1000088 
-> http://vocab.getty.edu/ontology#prefLabelGVP
-> http://vocab.getty.edu/tgn/term/120-nb 
=> Norge@nb

Thanks for giving it a try... =o)

**Comment by matteoLorenzini** [comment]
Done: New dump files: 

- tgn_@_labelled_lat_longNOconcat.csv 

- tgn_@_labelled_lat_longCONCAT.csv

**Comment by thomashaensli** [comment]
thanks, Matteo!

Data are perfect now!
Thomas


Von: matteoLorenzini <notifications@github.com><mailto:notifications@github.com>
Antworten: gtadigital/SPARQL_Data_Analysis <reply@reply.github.com><mailto:reply@reply.github.com>
Datum: 25. Juni 2019 at 18:46:44
An: gtadigital/SPARQL_Data_Analysis <sparql_data_analysis@noreply.github.com><mailto:sparql_data_analysis@noreply.github.com>
CC: Thomas Haensli <thomas.haensli@gta.arch.ethz.ch><mailto:thomas.haensli@gta.arch.ethz.ch>, Comment <comment@noreply.github.com><mailto:comment@noreply.github.com>
Betreff:  Re: [gtadigital/SPARQL_Data_Analysis] Missing languages in output (#2)


Closed #2<https://github.com/gtadigital/SPARQL_Data_Analysis/issues/2>.
